### ISSUE TITLE
Recommendation: Make a general rule for flex containers

### ISSUE THREAD

**Issue by melissamcewen** [amberoar/teacozy#6]
So your CSS is really well organized but in the end it's worth looking at the different parts and asking what they share. In this case, they can share a general flex-box style. You can then make a class for it like this

```css
.flex-container {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}

```

and apply the class to things like
`    <div id="mission" class="flex-container">`
```
    <div id="store">
      <h2>Tea of the Month</h2>
      <h4>What's Steeping at The Tea Cozy?</h4>
      <div class="flex-container items">
```

```    
<div id="locations">
      <h2>Locations</h2>
      <div class="flex-container locations">
```

This simplifies things greatly
